name: AdamAsmaca
options:
  minimumXcodeGenVersion: 2.37.0
  deploymentTarget:
    iOS: "15.0"

settings:
  base:
    SWIFT_VERSION: 5.9
    PRODUCT_BUNDLE_IDENTIFIER: com.example.AdamAsmaca
    DEVELOPMENT_TEAM: ""

packages: {}

targets:
  AdamAsmaca:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - App
      - Resources
    settings:
      base:
        INFOPLIST_FILE: App/Info.plist
    info:
      path: App/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UILaunchScreen:
          UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    scheme:
      testTargets: []